### ISSUE TITLE
Time zone labels are swapped

### ISSUE THREAD

**Issue by Malahovskys** [epam/clocks#321]
**Describe the bug**
Time zone labels are swapped

**To Reproduce**

1. Go to https://clocks.lab.epam.com/?locations=eyJNaW5zazUzLjg5OTk3NzQ0Ijp7ImNpdHkiOiJNaW5zayIsImxhdCI6NTMuODk5OTc3NDQsIm9mZnNldCI6LTE4MH0sIkxvbmRvbjUxLjQ5OTk5NDczIjp7ImNpdHkiOiJMb25kb24iLCJsYXQiOjUxLjQ5OTk5NDczLCJvZmZzZXQiOi02MH0sIldhcnNhdzUyLjI1MDAwMDYzIjp7ImNpdHkiOiJXYXJzYXciLCJsYXQiOjUyLjI1MDAwMDYzLCJvZmZzZXQiOi0xMjB9LCJUYmlsaXNpNDEuNzI1MDA5OTkiOnsiY2l0eSI6IlRiaWxpc2kiLCJsYXQiOjQxLjcyNTAwOTk5LCJvZmZzZXQiOi0yNDB9LCJQcmFndWU1MC4wODMzMzcwMSI6eyJjaXR5IjoiUHJhZ3VlIiwibGF0Ijo1MC4wODMzMzcwMSwib2Zmc2V0IjotMTIwfSwiTGlzYm9uMzguNzIyNzIyODgiOnsiY2l0eSI6Ikxpc2JvbiIsImxhdCI6MzguNzIyNzIyODgsIm9mZnNldCI6LTYwfSwiVGFzaGtlbnQ0MS4zMTE3MDE4OCI6eyJjaXR5IjoiVGFzaGtlbnQiLCJsYXQiOjQxLjMxMTcwMTg4LCJvZmZzZXQiOi0zMDB9fQ%3D%3D
2. Or refresh the page
3. See error

**Expected behavior**
London is Europe/London
Minsk is Europe/Minsk

**Screenshots**
https://i.imgur.com/xs10PC7.png

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser: Chrome Version 103.0.5060.134 (Official Build) (64-bit)

Other notes:
- QA Engineer is required

**Comment by BakhromSadullaev** [comment]
Issue will be resolved in new release of app (v 2.4.4)
