### ISSUE TITLE
Dashboard display wrong time for some cities

### ISSUE THREAD

**Issue by VladimirOsipov1** [epam/clocks#322]
**Describe the bug**
Dashboard display wrong time zone for Novi Sad and Minsk

**To Reproduce**

1. Go to (https://clocks.lab.epam.com/?locations=eyJBbnRhbHlhMzYuODg5OTgyMTIiOnsiY2l0eSI6IkFudGFseWEiLCJsYXQiOjM2Ljg4OTk4MjEyLCJvZmZzZXQiOi0xODB9LCJNaW5zazUzLjg5OTk3NzQ0Ijp7ImNpdHkiOiJNaW5zayIsImxhdCI6NTMuODk5OTc3NDQsIm9mZnNldCI6LTE4MH0sIk5vdmkgU2FkNDUuMjUwMzc2MiI6eyJjaXR5IjoiTm92aSBTYWQiLCJsYXQiOjQ1LjI1MDM3NjIsIm9mZnNldCI6LTEyMH19)
2. reload the page
3. see the error

**Expected behavior**
Correct time is displayed for all cities

**Screenshots**
![clocks](https://user-images.githubusercontent.com/110054572/181071907-95617af7-2fc6-44f5-a385-0e82987e8dac.PNG)
![clocks 1](https://user-images.githubusercontent.com/110054572/181072498-ac6d0074-a87f-41d8-9106-f0fb4aba0f9b.PNG)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Google Chrome
- Version 103.0.5060.134**

**Additional context**
Unstable bug. When I first open it showed correct times.

**Comment by shokhrukh-epam** [comment]
The issue will be resolved in the new version of the app (v2.4.4).
