### ISSUE TITLE
Remove Drag&Drop

### ISSUE THREAD

**Issue by ArturSalikhovEPAM** [epam/clocks#326]
Given the new plan for functionality, requests and feedback, we need to simplify the LocationBlock component and remove all functionality related to Drag&Drop. 

- Remove Drag&Drop functionality
- Remove AutoSorting checkbox in settings (AutoSorting should work as a default behavior)
- Simplify LocationBlock component by splitting it to several components

**Comment by BakhromSadullaev** [comment]
Issue will be resolved in new release of app
