### ISSUE TITLE
Remove sticky Pin & Comment icons for Home location 

### ISSUE THREAD

**Issue by zahhar** [epam/clocks#341]
**Is your feature request related to a problem? Please describe.**
When I selected my home location, its card always shows "Pin" & "Comment" icons that I find annoying and looking ugly. As a user, I do not need to see all the time those icons — there are no benefits. "Home" card is already distinguished from others by its colored border + by "Local time" text inside. No need to show "Pin" — I will never click it again. 

**Describe the solution you'd like**
Make "Pin" and "Comment" icons behave on all cards exactly the same: appear on hower / on tap into the card. 

**Additional context**

<img width="955" alt="Bildschirmfoto 2022-07-26 um 22 14 40" src="https://user-images.githubusercontent.com/48603/188622746-2f1ad007-849b-45ea-a080-567dd9bb02fe.png">

**Comment by AndreiNavitski** [comment]
@SheratriumEPAM, please check and approve

**Comment by AndreiNavitski** [comment]
@SheratriumEPAM, please check and approve
