### ISSUE TITLE
Allow users to hide footer

### ISSUE THREAD

**Issue by zahhar** [epam/clocks#342]
**Is your feature request related to a problem? Please describe.**
As a user who embeds the Clocks dashboard into MS Teams or Confluence page, I want to remove the footer: it is not needed in that context and only consumes valuable vertical space. 

**Describe the solution you'd like**
Probably good idea will be if Footer appears by default, but has a control in Settings that allows user to deselect it. By default checkbox "Display footer" is ON and footer is visible. User may switch it OFF, then footer disappears. 

**Additional context**
This is how page looks now once embedded into MS Teams:

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/48603/188623811-fe8b051d-4a47-4ff3-9010-0c2479635b27.png">

**Comment by AndreiNavitski** [comment]
@SheratriumEPAM, please check and approve
