### ISSUE TITLE
Replace "Cancel" buttons with "X" in the upper-right corners

### ISSUE THREAD

**Issue by zahhar** [epam/clocks#343]
**Is your feature request related to a problem? Please describe.**
Current UI is inconsistent: for Add Location panel we already use "X" in the upper-right corner to close the panel. For modal pop-ups, for some reason, we decided to use "Cancel" button. Users will benefit from more consistent UI.

**Describe the solution you'd like**
Proposal is to replace "Cancel" buttons in modals with "X" icons in the upper-right corner. 
Affected: 
* Comment modal
* Help info modal
* Settings modal

**Describe alternatives you've considered**
* Add Cancel button to Location panel and remove "X" from there — looks heavyweight
* Have both Cancel button and "X" everywhere — looks also heavyweight

**Additional context**
<img width="524" alt="Bildschirmfoto 2022-09-06 um 13 28 37" src="https://user-images.githubusercontent.com/48603/188626441-c5a0e6f8-d592-484a-ad4d-84515ae8b74a.png">

<img width="267" alt="Bildschirmfoto 2022-09-06 um 13 28 54" src="https://user-images.githubusercontent.com/48603/188626458-9006b1e0-e1a8-4e5c-b89f-eb069d779ed3.png">

<img width="466" alt="Bildschirmfoto 2022-09-06 um 13 29 12" src="https://user-images.githubusercontent.com/48603/188626470-5cd82a42-8c8a-4275-9e7e-2363e7620cf2.png">

**Comment by AndreiNavitski** [comment]
@SheratriumEPAM, please review and aprrove.

**Comment by AndreiNavitski** [comment]
@SheratriumEPAM, please check and approve
