### ISSUE TITLE
Launch check-list

### ISSUE THREAD

**Issue by AndreiNavitski** [epam/clocks#81]
- [x] Deployment to clocks.lab.epam.com
- [x] Separate production and development environments
- Get approve from 
   - [x] Dmitry Galyuk, 
   - [x] Zahhar Kirillov, 
   - [x] Andrei Navitski2, 
   - [x] Artur Salikhov
- [x] Send email WFT PM with announcement 
- [x] Give a non-standard badges for team members (ask for Practice/Max/GDO)
  - [x] Juratbek Makhammadaliev
  - [x] Nizomiddin Abdumalikov
  - [x] Shokhrukh Yuldashev
  - [x] Bakhromjon Sadullaev
  - [x] Dmitry Galyuk 
  - [x] Zahhar Kirillov
  - [x] Tamas Hoffman
  - [x] Arthur Salikhov
- [x] Give standard badge for those who helped:  
  - [x] Maxim Klivenko
  - [x] Vital Zheltanoha
  - [x] Ivan Filko
  - [x] Vassili Makeev
- [x] Team rotation

**Comment by zahhar** [comment]
Closing as done: remaining items moved to #364
